-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Gegenereerd op: 11 dec 2025 om 11:52
-- Serverversie: 10.4.32-MariaDB
-- PHP-versie: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `utrechtsarchief`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `colofon`
--

CREATE TABLE `colofon` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `last_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

--
-- Gegevens worden geëxporteerd voor tabel `colofon`
--

INSERT INTO `colofon` (`id`, `title`, `content`, `last_updated`) VALUES
(1, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website.', '2025-12-03 10:02:51'),
(2, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website.\r\n\r\ndoei', '2025-12-03 10:12:26'),
(3, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website.\r\n', '2025-12-03 10:12:43'),
(4, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website.\r\n\r\ndoeidoei\r\n', '2025-12-03 10:15:28'),
(5, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website.\r\n', '2025-12-03 10:16:04'),
(6, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website.\r\ntest\r\n', '2025-12-09 08:04:18'),
(7, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website.\r\ntest', '2025-12-09 09:31:20'),
(8, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website.\r\ntest\r\n', '2025-12-09 09:31:28'),
(9, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website. test\r\n', '2025-12-09 09:35:37'),
(10, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website. test\r\n', '2025-12-09 09:36:38'),
(11, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website. test\r\n\r\n', '2025-12-09 09:47:01'),
(17, 'Colofon', 'Deze website is tot stand gekomen als onderdeel van een educatief en creatief ontwikkeltraject, uitgevoerd door Mylène Zijlstra en Iris Govaard. Met veel zorg, aandacht en enthousiasme hebben wij gewerkt aan het ontwerp, de vormgeving en de inhoudelijke opbouw van deze website. Ons doel was om een toegankelijke, overzichtelijke en informatieve online omgeving te creëren waarin het erfgoed van Utrecht op een boeiende manier wordt gepresenteerd.\r\n\r\n  Opdrachtgever\r\n\r\n  Dit project is ontwikkeld in opdracht van Het Utrechts Archief, de bewaarplaats van de rijke geschiedenis van de stad en provincie Utrecht. Door deze samenwerking kregen wij de kans om diep in het historische materiaal te duiken en dit te vertalen naar een digitaal eindresultaat dat aansluit bij de missie van het archief: het delen, bewaren en toegankelijk maken van cultureel erfgoed.\r\n\r\n  Contactpersoon\r\n\r\n  Gedurende het gehele traject hadden wij nauw contact met Ellen Blom, die vanuit Het Utrechts Archief de rol van begeleider en aanspreekpunt vervulde. Haar feedback, deskundigheid en betrokkenheid waren van onschatbare waarde voor de ontwikkeling van de website. Dankzij haar begeleiding kon het project groeien van een concept naar een volledig functionele en inhoudelijk sterke website.\r\n\r\n  Onderwijsinstelling\r\n\r\n  Dit project is mede mogelijk gemaakt door het Grafisch Lyceum Utrecht. De school bood de ruimte, begeleiding en faciliteiten die nodig waren om dit werk te realiseren. Binnen onze opleiding kregen wij de kans om onze creatieve en technische vaardigheden verder te ontwikkelen en in de praktijk te brengen, met dit eindproduct als resultaat.\r\n\r\n  Ontwerp & Realisatie\r\n\r\n  Conceptontwikkeling: Mylène Zijlstra & Iris Govaard\r\n  Vormgeving & UX-design: Mylène Zijlstra & Iris Govaard\r\n  Tekst & Contentselectie: In samenwerking met Het Utrechts Archief\r\n  Technische uitwerking & Websitebouw: Mylène Zijlstra & Iris Govaard\r\n\r\n  Wij hebben gebruikgemaakt van diverse digitale hulpmiddelen om het ontwerp en de bouw van de website zo efficiënt en zorgvuldig mogelijk te realiseren. Daarbij lag de nadruk op toegankelijkheid, consistentie in vormgeving en een gebruikservaring die past bij een breed publiek.\r\n\r\n  Dankwoord\r\n\r\n  Wij willen graag Het Utrechts Archief, en in het bijzonder Ellen Blom, bedanken voor hun vertrouwen, betrokkenheid en ondersteuning. Ook spreken wij onze dank uit aan het Grafisch Lyceum Utrecht voor het bieden van de mogelijkheden om dit project te ontwikkelen binnen onze opleiding. Tot slot bedanken wij iedereen die op enige wijze heeft bijgedragen aan de totstandkoming van deze website. \r\n\r\n', '2025-12-09 09:47:18');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `hotspots`
--

CREATE TABLE `hotspots` (
  `id` int(11) NOT NULL,
  `image_id` int(11) NOT NULL,
  `pos_top` int(11) DEFAULT 20,
  `pos_left` int(11) DEFAULT 20,
  `description` text DEFAULT NULL,
  `description_nl` text DEFAULT NULL,
  `description_en` text DEFAULT NULL,
  `remark_nl` text DEFAULT NULL,
  `remark_en` text DEFAULT NULL,
  `extra_info_nl` text DEFAULT NULL,
  `extra_info_en` text DEFAULT NULL,
  `extra_image` varchar(255) DEFAULT NULL,
  `remark_top` int(11) DEFAULT NULL,
  `remark_left` int(11) DEFAULT NULL,
  `extra_top` int(11) DEFAULT NULL,
  `extra_left` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Gegevens worden geëxporteerd voor tabel `hotspots`
--

INSERT INTO `hotspots` (`id`, `image_id`, `pos_top`, `pos_left`, `description`, `description_nl`, `description_en`, `remark_nl`, `remark_en`, `extra_info_nl`, `extra_info_en`, `extra_image`, `remark_top`, `remark_left`, `extra_top`, `extra_left`) VALUES
(1, 1, 393, 570, 'Afbeelding van de titelpagina van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon', 'Afbeelding van de titelpagina van het Panorama van Utrecht, op de lithostenen\ngetekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed.\nHerfkens en zoon.', 'Image of the title page of the Panorama of Utrecht, on the litho stones\ndrawn by J. Bos, printed by P.W. van de Weijer and published in July 1859 by the Wed.\nHerfkens and son.', 'Titelpagina van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Title page of the Panorama of Utrecht, drawn on the litho stones by J. Bos, printed by P.W. van de Weijer and published in July 1859 by the Wed. Herfkens and son. The panorama is a circular walk with ever-changing views of the city of Utrecht from the canals. It consists of four joined, zigzag folded leaves with a total length of 5.82 meters. Each image between two folds is described separately (no. 135001-135033). With a second, identical copy (only different title page): no. 135001-1 - 135033-1.', 'safds', 'dewgfds', '', 249, 934, 297, 588),
(2, 2, 226, 826, 'Gezicht over de Wittevrouwenbrug in de Wittevrouwenstraat te Utrecht met het douanekantoor (de latere politiepost Wittevrouwen) en de Willemskazerne.', 'Gezicht op de gevangenis aan het Wolvenplein te Utrecht op het vroegere bolwerk Wolvenburg, met rechts een huis op de afgegraven stadswal bij de Wolvenstraat.', 'View of the prison at Wolvenplein in Utrecht on the former Wolvenburg stronghold, with a house on the right on the excavated city wall near Wolvenstraat.', 'Gezicht over de Wittevrouwenbrug in de Wittevrouwenstraat te Utrecht met het douanekantoor (de latere politiepost Wittevrouwen) en de Willemskazerne.', 'View across the Wittevrouwenbrug in the Wittevrouwenstraat in Utrecht with the customs office (later the Wittevrouwen police station) and the Willemskazerne.', 'csd', 'sdd', '', 150, 250, 180, 280),
(3, 3, 188, 323, 'Gezicht op de gevangenis aan het Wolvenplein te Utrecht op het vroegere bolwerk Wolvenburg, met rechts een huis op de afgegraven stadswal bij de Wolvenstraat.', 'Gezicht op de gevangenis aan het Wolvenplein te Utrecht op het vroegere bolwerk Wolvenburg, met rechts een huis op de afgegraven stadswal bij de Wolvenstraat.', 'View of the prison on Wolvenplein in Utrecht on the former Wolvenburg stronghold, with a house on the right on the excavated city wall at Wolvenstraat.', 'Pagina 3 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Page 3 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described (nos. 135001-135033). With a second, identical copy (only with a different title page): nos. 135001-1 - 135033-1.', '', '', '', 282, 751, 240, 340),
(4, 4, 172, 958, 'Gezicht op de uitmonding van de Plompetorengracht te Utrecht in de stadsbuitengracht, in het midden de bomen langs de Noorderkade en rechts een gedeelte van het Begijnebolwerk.', 'Pagina 4 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Page 4 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described (nos. 135001-135033). With a second, identical copy (only with a different title page): nos. 135001-1 - 135033-1.', 'Gezicht op de uitmonding van de Plompetorengracht te Utrecht in de stadsbuitengracht, in het midden de bomen langs de Noorderkade en rechts een gedeelte van het Begijnebolwerk.', 'View of the mouth of the Plompetorengracht canal in Utrecht into the city\'s outer moat, with the trees along the Noorderkade in the middle and part of the Begijnebolwerk on the right.', '', '', '', 220, 320, 240, 340),
(5, 5, 274, 273, 'Beschrijving panorama 5', 'Gezicht op het Begijnebolwerk te Utrecht.', 'View of the Beguinage stronghold in Utrecht.', 'Pagina 5 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1. Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.\n(nr. 135001-135033).', 'Page 5 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described. With a second, identical copy (only with a different title page): no. 135001-1 - 135033-1. With a second, identical copy (only with a different title page): no. 135001-1 - 135033-1.\n(no. 135001-135033).', '', '', '', 173, 612, 240, 340),
(6, 6, 250, 680, 'Beschrijving panorama 6', 'Pagina 6 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1. Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.\n(nr. 135001-135033).', 'Page 6 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described. With a second, identical copy (only with a different title page): no. 135001-1 - 135033-1. With a second, identical copy (only with a different title page): no. 135001-1 - 135033-1.\n(no. 135001-135033).', 'Gezicht op een gedeelte van het Begijnebolwerk (links) en de Van Asch van Wijckskade te Utrecht.', 'View of part of the Begijnebolwerk (left) and the Van Asch van Wijckskade in Utrecht.', '', '', '', 220, 320, 240, 340),
(7, 7, 223, 611, 'Beschrijving panorama 7', 'Gezicht op de Van Asch van Wijckskade te Utrecht, de Weerdbarrière en de\nWeerdbrug en rechts de Noorderkade met de stadswaag en stadskraan.', 'View of the Van Asch van Wijckskade in Utrecht, the Weerd Barrier and the\nWeerdbrug and on the right the Noorderkade with the city weighing house and city crane.', 'Pagina 7 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Page 7 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described (nos. 135001-135033). With a second, identical copy (only with a different title page): nos. 135001-1 - 135033-1.', '', '', '', 220, 320, 240, 340),
(8, 8, 207, 704, 'Beschrijving panorama 8', ' Gezicht op de Noorderkade te Utrecht, de Koninklijke Fabriek van\nLandbouwkundige Werktuigen, bierbrouwerij De Krans en het Paardenveld met de molen De Rijn\nen Zon.', 'View of the Noorderkade in Utrecht, the Royal Factory of\nAgricultural Implements, the De Krans brewery, and the Paardenveld with the De Rijn\nen Zon windmill.', 'Pagina 8 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Page 8 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described (nos. 135001-135033). With a second, identical copy (only with a different title page): nos. 135001-1 - 135033-1.', '', '', '', 220, 320, 240, 340),
(9, 9, 155, 617, 'Beschrijving panorama 9', 'Gezicht op het Paardenveld te Utrecht met de molen De Meiboom en rechts een\nwas- en badhuis, de latere Wasch- en Badinrichting van W. de Rijk.', 'View of the Paardenveld in Utrecht with the De Meiboom windmill and, on the right, a washhouse and bathhouse, later the W. de Rijk Washing and Bathing Facility.', ' Badhuizen werden sinds eind 19e\neeuw gebouwd, toen er een grotere aandacht kwam voor hygiëne, gezondheid en levensstijl. De\nvraag naar hygiënische baden nam toe door industrialisatie en verstedelijking, wat leidde tot de\nbouw van openbare badhuizen, waar tegen betaling een bad of douche kon worden genomen.\n', 'Bathhouses began to be built at the end of the 19th century, when greater attention was paid to hygiene, health, and lifestyle. The demand for hygienic baths increased due to industrialization and urbanization, leading to the construction of public bathhouses where people could take a bath or shower for a fee.', '', '', '', 343, 983, 240, 340),
(10, 10, 207, 185, 'Beschrijving panorama 10', ' Gezicht over de Catharijnebrug te Utrecht op een groot appartementengebouw, het\ndouanekantoortje (de Catharijnebarrière), een herenhuis (later Bierhuis De Hoop) en de\ngasfabriek van W.H. de Heus op en bij het noordwestelijke bastion van het vroegere kasteel\nVredenburg.\n', 'View across the Catharijne Bridge in Utrecht of a large apartment building, the customs office (the Catharijne Barrier), a mansion (later Bierhuis De Hoop), and the W.H. de Heus gasworks on and near the northwestern bastion of the former Vredenburg Castle.', 'Pagina 10 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Page 10 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described (nos. 135001-135033). With a second, identical copy (only with a different title page): nos. 135001-1 - 135033-1.', '', '', '', 312, 366, 240, 340),
(11, 11, 87, 268, 'Beschrijving panorama 11', 'Gezicht op de koperpletterij van W.H. de Heus met het zuidwestelijke bastion van\nhet vroegere kasteel Vredenburg en rechts de Rijnkade te Utrecht.', 'View of the copper mill of W.H. de Heus with the southwestern bastion of the former Vredenburg Castle and, on the right, the Rijnkade in Utrecht.', 'Pagina 11 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Page 11 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described (nos. 135001-135033). With a second, identical copy (only with a different title page): nos. 135001-1 - 135033-1.', '', '', '', 295, 842, 240, 340),
(12, 12, 250, 839, 'Beschrijving panorama 12', 'Gezicht over de Willemsbrug op de Rijnkade te Utrecht, het hek met de\ndouanekantoortjes aan weerszijden van de brug (de Willemsbarrière) en rechts van de brug het\nbegin van het in Engelse landschapsstijl aangelegde singelplantsoen', 'View across the Willemsbrug onto the Rijnkade in Utrecht, the fence with the customs offices on either side of the bridge (the Willems Barrier) and to the right of the bridge the beginning of the English landscaped canal park', 'Pagina 12 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Page 12 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described (nos. 135001-135033). With a second, identical copy (only with a different title page): nos. 135001-1 - 135033-1.', '', '', '', 176, 290, 240, 340),
(13, 13, 209, 245, 'Beschrijving panorama 13', 'Gezicht op het in Engelse landschapsstijl aangelegde singelplantsoen te Utrecht\nmet het theehuis van de oud-rooms-katholieke aartsbisschop en rechts het hospitaal van het\nDuitse Huis. Het kruis boven het langgerekte rode dak is van de Dominicuskerk op de\nMariaplaats.', 'View of the English-style canalside park in Utrecht\nwith the teahouse of the Old Roman Catholic archbishop and, on the right, the hospital of the\nDuitse Huis. The cross above the elongated red roof belongs to the Dominican Church on\nMariaplaats.', 'Pagina 13 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Page 13 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described (nos. 135001-135033). With a second, identical copy (only with a different title page): nos. 135001-1 - 135033-1.', '', '', '', 313, 713, 240, 340),
(14, 14, 267, 409, 'Beschrijving panorama 14', 'Gezicht op het in Engelse landschapsstijl aangelegde singelplantsoen te Utrecht ter hoogte van de Zeven Steegjes.', 'View of the English landscape-style canal park in Utrecht at the Zeven Steegjes.', 'Pagina 14 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Page 14 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described (nos. 135001-135033). With a second, identical copy (only with a different title page): nos. 135001-1 - 135033-1.', '', '', '', 241, 1145, 240, 340),
(15, 15, 258, 438, 'Beschrijving panorama 15', ' Gezicht op het singelplantsoen te Utrecht met het Bartholomeusgasthuis.', 'View of the canal park in Utrecht with the Bartholomeus Gasthuis.', 'Pagina 15 van het Panorama van Utrecht, op de lithostenen getekend door J. Bos, gedrukt bij P.W. van de Weijer en in juli 1859 uitgegeven door de Wed. Herfkens en zoon. Het panorama is een rondwandeling met steeds wisselende gezichten op de stad Utrecht vanaf de singels. Het bestaat uit vier aaneengeplakte, zigzag gevouwen bladen met een totale lengte van 5,82 meter. Elk beeld tussen twee vouwen is afzonderlijk beschreven (nr. 135001-135033). Met een tweede, identiek exemplaar (alleen afwijkende titelpagina): nr. 135001-1 - 135033-1.', 'Page 15 of the Panorama of Utrecht, drawn on lithographic stones by J. Bos, printed by P.W. van de Weijer, and published in July 1859 by the widow Herfkens and son. The panorama is a circular walk with constantly changing views of the city of Utrecht from the canals. It consists of four joined, zigzag-folded sheets with a total length of 5.82 meters. Each image between two folds is individually described (nos. 135001-135033). With a second, identical copy (only with a different title page): nos. 135001-1 - 135033-1.', '', '', '', 235, 924, 240, 340),
(16, 16, 20, 20, 'Beschrijving panorama 16', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(17, 17, 353, 856, 'Beschrijving panorama 17', '', '', '', '', '', '', '', 220, 320, 240, 340),
(18, 18, 20, 20, 'Beschrijving panorama 18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(19, 19, 20, 20, 'Beschrijving panorama 19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(20, 20, 20, 20, 'Beschrijving panorama 20', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(21, 21, 162, 732, 'Beschrijving panorama 21', '', '', '', '', '', '', '', 216, 882, 240, 340),
(22, 22, 20, 20, 'Beschrijving panorama 22', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(23, 23, 20, 20, 'Beschrijving panorama 23', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(24, 24, 20, 20, 'Beschrijving panorama 24', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(25, 25, 20, 20, 'Beschrijving panorama 25', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(26, 26, 305, 858, 'Beschrijving panorama 26', '', '', '', '', '', '', '', 220, 320, 240, 340),
(27, 27, 20, 20, 'Beschrijving panorama 27', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(28, 28, 20, 20, 'Beschrijving panorama 28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(30, 30, 20, 20, 'Beschrijving panorama 30', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(31, 31, 200, 300, NULL, 'Beschrijving NL 31', 'Description EN 31', NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(32, 32, 150, 250, NULL, 'Beschrijving NL 32', 'Description EN 32', NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340),
(33, 33, 180, 280, NULL, 'Beschrijving NL 33', 'Description EN 33', NULL, NULL, NULL, NULL, NULL, 220, 320, 240, 340);

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `hotspot_extra`
--

CREATE TABLE `hotspot_extra` (
  `id` int(11) NOT NULL,
  `hotspot_id` int(11) NOT NULL,
  `info_nl` text DEFAULT NULL,
  `info_en` text DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `pos_top` int(11) DEFAULT 0,
  `pos_left` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Gegevens worden geëxporteerd voor tabel `hotspot_extra`
--

INSERT INTO `hotspot_extra` (`id`, `hotspot_id`, `info_nl`, `info_en`, `image`, `pos_top`, `pos_left`) VALUES
(2, 1, 'Het Panorama van Utrecht bestaat uit vier aaneengeplakte, zigzag gevouwen bladen\nmet een totale lengte van 5,82 meter. Het panorama is een meterslange tekening van een\nrondwandeling om het centrum van Utrecht, met steeds wisselend uitzicht vanaf de singels. Het geeft een heel precies beeld van hoe de stad in 1859 er uitzag en het leuke is dat je ook het\nverloop van de seizoenen in de tekening terugziet.', 'The Panorama of Utrecht consists of four pasted, zigzag-folded sheets with a total length of 5.82 meters. The panorama is a meter-long drawing of a circular walk around the center of Utrecht, with ever-changing views from the canals. It\ngives a very precise picture of what the city looked like in 1859 and the nice thing is that you can also see it the course of the seasons in the drawing.', '', 168, 285),
(5, 4, 'Afbeelding van het overhaalschuitje over de Stadsbuitengracht ter hoogte van de Lange Smeestraat te Utrecht.', 'Image of the ferry boat crossing the Stadsbuitengracht canal near the Lange Smeestraat in Utrecht.', 'X102363 - 76293.jpg', 291, 703),
(6, 8, 'Gezicht op de stoombierbrouwerij De Krans (Nieuwekade 30) te\nUtrecht. Vanaf de middeleeuwen werd er in Utrecht volop bier gebrouwen. Tot ver in de 19e eeuw\nwerd hier grachtenwater voor gebruikt. In de twintigste eeuw verloren de Utrechtse brouwerijen\nde concurrentiestrijd met die uit Amsterdam en verdwenen de brouwerijen in de stad.', 'View of the De Krans steam brewery (Nieuwekade 30) in\nUtrecht. From the Middle Ages onward, beer was brewed extensively in Utrecht. Canal water was used for this until well into the 19th century. In the twentieth century, Utrecht\'s breweries\nlost their competitive edge with those in Amsterdam, and the city\'s breweries disappeared.', '669.jpg', 302, 941),
(8, 10, 'Gezicht op de stadsbuitengracht en de Catharijnebrug te Utrecht, uit\nhet zuidwesten, met op de achtergrond een gebouw waarin meerdere woonhuizen zijn\ngecombineerd aan de latere Catharijnekade. Omstreeks 1859.', 'View of the city\'s outer moat and the Catharijne Bridge in Utrecht, from\nthe southwest, with a building in the background that combines several houses\non what is now the Catharijnekade. Circa 1859.', NULL, 381, 745),
(9, 10, 'Gezicht op de Stadsbuitengracht en de Catharijnebrug te Utrecht, uit\nhet noordwesten, met links het commiezenhuisje, daarachter de schoorsteen van de gasfabriek\nvan W.H. de Heus op het Vredenburg en in het midden een herenhuis (later bierhuis De Hoop).\nOmstreeks 1859.', 'View of the Stadsbuitengracht and the Catharijnebrug in Utrecht, from\nthe northwest, with the customs house on the left, behind it the chimney of the gasworks\nof W.H. de Heus on the Vredenburg, and in the center a mansion (later De Hoop beer house).\nCirca 1859.', NULL, 166, 1022),
(10, 10, 'Gezicht op de gasfabriek van W.H. de Heus op het Vredenburg te\nUtrecht, met daarbij de \"Nieuwejaars Heil- en Zegenwensch\" van de gaslantaarnopstekers bij de\naanvang van het jaar 1857.', 'View of the W.H. de Heus gasworks on the Vredenburg in\nUtrecht, with the \"New Year\'s Greetings and Blessings\" from the gas lamplighters at the beginning of the year 1857.', NULL, 348, 1265),
(11, 10, 'Gezicht vanaf de Catharijnebrug op de stadsbuitengracht te Utrecht, uit\nhet noordwesten, met links de gasfabriek van W.H. de Heus aan het Vredenburg. De steenmassa\nis het noordwestelijke bastion van het vroegere kasteel Vredenburg. Foto uit omstreeks 1859', 'View from the Catharijne Bridge of the outer city moat in Utrecht,\nfrom the northwest, with the W.H. de Heus gasworks at Vredenburg on the left. The stone mass\nis the northwestern bastion of the former Vredenburg Castle. Photo from circa 1859', NULL, 119, 570),
(12, 12, ' Gezicht vanaf de Catharijnesingel te Utrecht over de Willemsbrug met\nde beide commiezenhuisjes uit het zuidwesten, met links het hoekhuis aan de Rijnkade, rechts\neen herenhuis in het Willemsplantsoen en op de achtergrond de Mariaplaats en de Buur- en\nDomtoren. Omstreeks 1850.', 'View from the Catharijnesingel in Utrecht across the Willemsbrug bridge with\nthe two customs houses from the southwest, with the corner house on the Rijnkade on the left,\na mansion in the Willemsplantsoen on the right, and in the background the Mariaplaats and the Buurtoren and\nDomtoren. Circa 1850.', '', 366, 1143),
(13, 14, 'Plattegrond van de stad Utrecht met directe omgeving; met weergave\nvan het stratenplan (deels met straatnamen), wegen en watergangen en aanduiding van de\nbelangrijke gebouwen. Met weergave van alle groenvoorzieningen, waaronder de plantsoenen,\ndoor Zocher aangelegd op de geslechte wallen en bolwerken, aangeduid als \"Nieuwe\nwandeling\". Met lijst van belangrijke gebouwen en overige objecten. Datering rond 1858.', 'Map of the city of Utrecht and its immediate surroundings; showing\nthe street layout (partly with street names), roads and waterways, and an indication of\nimportant buildings. It also shows all green spaces, including the public gardens,\ndesignated by Zocher on the demolished ramparts and bastions, designated as the \"Nieuwe Wandeling\" (New Walk). Includes a list of important buildings and other objects. Dating circa 1858.', NULL, 263, 694);

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `panorama`
--

CREATE TABLE `panorama` (
  `id` int(11) NOT NULL,
  `filename` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Gegevens worden geëxporteerd voor tabel `panorama`
--

INSERT INTO `panorama` (`id`, `filename`) VALUES
(1, '1.jpg'),
(2, '2.jpg'),
(3, '3.jpg'),
(4, '4.jpg'),
(5, '5.jpg'),
(6, '6.jpg'),
(7, '7.jpg'),
(8, '8.jpg'),
(9, '9.jpg'),
(10, '10.jpg'),
(11, '11.jpg'),
(12, '12.jpg'),
(13, '13.jpg'),
(14, '14.jpg'),
(15, '15.jpg'),
(16, '16.jpg'),
(17, '17.jpg'),
(18, '18.jpg'),
(19, '19.jpg'),
(20, '20.jpg'),
(21, '21.jpg'),
(22, '22.jpg'),
(23, '23.jpg'),
(24, '24.jpg'),
(25, '25.jpg'),
(26, '26.jpg'),
(27, '27.jpg'),
(28, '28.jpg'),
(29, '29.jpg'),
(30, '30.jpg'),
(31, '31.jpg'),
(32, '32.jpg'),
(33, '33.jpg');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password_hash` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Gegevens worden geëxporteerd voor tabel `users`
--

INSERT INTO `users` (`id`, `username`, `password_hash`) VALUES
(1, 'admin', '$2y$10$swy6dS3rCzKxUHFijtmM8u7jJRf7/dP23oLUS8GCWLlQZ9QgycV2S');

--
-- Indexen voor geëxporteerde tabellen
--

--
-- Indexen voor tabel `colofon`
--
ALTER TABLE `colofon`
  ADD PRIMARY KEY (`id`);

--
-- Indexen voor tabel `hotspots`
--
ALTER TABLE `hotspots`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `image_id` (`image_id`);

--
-- Indexen voor tabel `hotspot_extra`
--
ALTER TABLE `hotspot_extra`
  ADD PRIMARY KEY (`id`),
  ADD KEY `hotspot_id` (`hotspot_id`);

--
-- Indexen voor tabel `panorama`
--
ALTER TABLE `panorama`
  ADD PRIMARY KEY (`id`);

--
-- Indexen voor tabel `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);

--
-- AUTO_INCREMENT voor geëxporteerde tabellen
--

--
-- AUTO_INCREMENT voor een tabel `colofon`
--
ALTER TABLE `colofon`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;

--
-- AUTO_INCREMENT voor een tabel `hotspots`
--
ALTER TABLE `hotspots`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;

--
-- AUTO_INCREMENT voor een tabel `hotspot_extra`
--
ALTER TABLE `hotspot_extra`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT voor een tabel `panorama`
--
ALTER TABLE `panorama`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=828;

--
-- AUTO_INCREMENT voor een tabel `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- Beperkingen voor geëxporteerde tabellen
--

--
-- Beperkingen voor tabel `hotspot_extra`
--
ALTER TABLE `hotspot_extra`
  ADD CONSTRAINT `hotspot_extra_ibfk_1` FOREIGN KEY (`hotspot_id`) REFERENCES `hotspots` (`image_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
